language: node_js

services:
  - couchdb

node_js:
  - "5"
sudo: false
script: npm run $COMMAND
before_script:
  - "npm install add-cors-to-couchdb"
  - "./node_modules/.bin/add-cors-to-couchdb"

env:
  matrix:
  - COMMAND=test
  - CLIENT=selenium:phantomjs COMMAND=test
  - COMMAND=coverage

branches:
  only:
  - master
